events {
    worker_connections 1024;
}

http {
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    log_format upstreamlog '$remote_addr - $host [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$upstream_addr"';
    access_log /var/log/nginx/access.log upstreamlog;

    limit_req_zone $binary_remote_addr zone=one:10m rate=10r/s;

    upstream backend_cluster {
        least_conn;
        server api-1:8000;
        server api-2:8000;
        server api-3:8000;
    }

    include /etc/nginx/conf.d/*.conf;
}